export const SELECT_HSL = 'SELECT_HSL' 
export const RESET_VALUE_OF_HSL = 'RESET_VALUE_OF_HSL' 

export const RESET_HUE = 'RESET_HUE'
export const RESET_SATURATION = 'RESET_SATURATION'
export const RESET_LIGHTNESS = 'RESET_LIGHTNESS'

export const GET_NEW_DEFAULT_FORMAT = 'GET_NEW_DEFAULT_FORMAT'
export const GET_RANDOM_COLOR = 'GET_RANDOM_COLOR'