const SELECT_HUE = 'SELECT_HUE'
const SELECT_SATURATION = 'SELECT_SATURATION'
const SELECT_LIGHTNESS = 'SELECT_LIGHTNESS'
const SELECT_ALPHA = 'SELECT_ALPHA'

const RESET_HUE = 'RESET_HUE'
const RESET_SATURATION = 'RESET_SATURATION'
const RESET_LIGHTNESS = 'RESET_LIGHTNESS'
const RESET_ALPHA = 'RESET_ALPHA'

const GET_RANDOM_COLOR = 'GET_RANDOM_COLOR'

export { SELECT_HUE, SELECT_SATURATION, SELECT_LIGHTNESS, SELECT_ALPHA, RESET_HUE, RESET_SATURATION, RESET_LIGHTNESS, RESET_ALPHA, GET_RANDOM_COLOR }