const SELECT_HSLA = 'SELECT_HSLA' 

const RESET_HUE = 'RESET_HUE'
const RESET_SATURATION = 'RESET_SATURATION'
const RESET_LIGHTNESS = 'RESET_LIGHTNESS'
const RESET_ALPHA = 'RESET_ALPHA'

const GET_NEW_DEFAULT_FORMAT = 'GET_NEW_DEFAULT_FORMAT'
const GET_RANDOM_COLOR = 'GET_RANDOM_COLOR'

export { SELECT_HSLA, RESET_HUE, RESET_SATURATION, RESET_LIGHTNESS, RESET_ALPHA, GET_RANDOM_COLOR, GET_NEW_DEFAULT_FORMAT }