export const REFORMAT_FORMATS = 'REFORMAT_FORMATS' 
export const IS_THE_SAME_TEXT_IN_CLIPBOARD = 'IS_THE_SAME_TEXT_IN_CLIPBOARD'
export const IS_THE_SAME_URL_IN_CLIPBOARD = 'IS_THE_SAME_URL_IN_CLIPBOARD'
