const INITIAL_HUE = 360
const INITIAL_SATURATION = 100
const INITIAL_LIGHTNESS = 50
const INITIAL_ALPHA = 1

const INITIAL_STATE = {
	hue: INITIAL_HUE,
	saturation: INITIAL_SATURATION,
	lightness: INITIAL_LIGHTNESS,
	alpha: INITIAL_ALPHA,
}

const COPIED_COLOR_HISTORY = {
	copiedColors: [],
	activeCopiedColor: null,
	activeTargetCopiedColor: 'hexa'
}

export { INITIAL_HUE, INITIAL_SATURATION, INITIAL_LIGHTNESS, INITIAL_ALPHA, INITIAL_STATE, COPIED_COLOR_HISTORY }